### ISSUE TITLE
还更新吗?

### ISSUE THREAD

**Issue by A2Data** [DeepSpaceHarbor/hexo-bridge#105]
可以提一些建议吗？

希望可以做成像文件管理器那样。 新建的 都在post下边。
目前比较乱。

**Comment by DeepSpaceHarbor** [comment]
👋 The plugin is still in active development and I'm open to suggestions. 

Could you add more details to your request? 
Unfortunately, google translate did not help, all I could understand is that, it's something related to the file manager.
