### ISSUE TITLE
关于新建文章。 About New Posts.

### ISSUE THREAD

**Issue by Meditly** [DeepSpaceHarbor/hexo-bridge#179]
<img width="452" alt="image" src="https://user-images.githubusercontent.com/60529895/208426561-8493a6aa-db17-4207-a99c-b166309b2df3.png">

- 首先，我非常喜欢您的项目，我认为这对我有很大帮助。但是我遇到了一些麻烦。

- First of all, I really like your project and I think it will help me a lot.But I ran into some trouble.

- 当我新建文章并且 hexo g 时总是会提示文件已经存在。  

- Whenever I create a new article and hexo g is always prompted that the file already exists.  

- 而且新建文章后 bridge 会跳转到一个错误的页面，查看hexo也发现了报错。

- In addition, the bridge redirects to an error page after creating a new article, and checking hexo also found the error.

**Comment by DeepSpaceHarbor** [comment]
Hey 👋, 
Thank you for the bug report! 
I was able to reproduce the behaviour and will start working on a fix asap.

**Comment by DeepSpaceHarbor** [comment]
I published a new version that should hopefully solve your problem.
Please try the following:
1. Update hexo-bridge to version `1.1.1`
2. Delete the `_bridge.yml` file from the blog folder directory
3. Run hexo
4. Try to create a new post.

In case you're still getting errors:
1. Open the `_bridge.yml` file from the blog folder directory. (or go to settings -> bridge)
2. Increase the value of `content_fetch_timeout` property and save the changes.
3. Restart hexo (must be done to read the new value).
4. Try again to create a new post/page.

**Comment by Meditly** [comment]
Thank you very much for your help and good luck!
