### ISSUE TITLE
How do i set up Password for access account of hexo-bridge?

### ISSUE THREAD

**Issue by TxcA** [DeepSpaceHarbor/hexo-bridge#38]
Thx.

**Comment by DeepSpaceHarbor** [comment]
Hexo-bridge doesn't support accounts and setting up password protection.

If you need to hide hexo-bridge behind a password, I'd recommend trying to mark bridge/* and api/* as password-protected directories using .htaccess.

**Comment by TxcA** [comment]
Thanks,
